# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0.xci
# IP: The module: 'timer_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0.xci
# IP: The module: 'timer_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
