set_property SRC_FILE_INFO {cfile:e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodHYGRO_0_0/timer_PmodHYGRO_0_0_board.xdc rfile:../../../timer.srcs/sources_1/bd/timer/ip/timer_PmodHYGRO_0_0/timer_PmodHYGRO_0_0_board.xdc id:1 order:EARLY used_in_board:yes scoped_inst:inst prop_thru_buffer:yes} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JD1} [get_ports Pmod_out_pin1_t]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JD2} [get_ports Pmod_out_pin2_t]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JD7} [get_ports Pmod_out_pin7_t]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JD8} [get_ports Pmod_out_pin8_t]
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JD9} [get_ports Pmod_out_pin9_t]
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JD10} [get_ports Pmod_out_pin10_t]
