######################################################################
#
# File name : tb_ip_clk_wiz_extend_simulate.do
# Created on: Sat Oct 19 10:56:16 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_ip_clk_wiz_extend xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_ip_clk_wiz_extend_wave.do}

view wave
view structure
view signals

do {tb_ip_clk_wiz_extend.udo}

run 1000ns
