######################################################################
#
# File name : tb_ip_clk_wiz_extend_wave.do
# Created on: Sat Oct 19 10:16:27 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
