######################################################################
#
# File name : tb_ip_clk_wiz_extend_compile.do
# Created on: Sat Oct 19 10:56:12 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim\\win64\\vlib modelsim_lib/work
F:\\modelsim\\win64\\vlib modelsim_lib/msim

F:\\modelsim\\win64\\vlib modelsim_lib/msim/xpm
F:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim\\win64\\vmap xpm modelsim_lib/msim/xpm
F:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim\\win64\\vlog  -incr -sv -work xpm  "+incdir+../../../../ip_clk_wiz_extend.gen/sources_1/ip/clk_wiz_0" \
"F:/Vivado/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"F:/Vivado/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

F:\\modelsim\\win64\\vcom  -93 -work xpm  \
"F:/Vivado/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \

F:\\modelsim\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../ip_clk_wiz_extend.gen/sources_1/ip/clk_wiz_0" \
"../../../../ip_clk_wiz_extend.gen/sources_1/ip/ila_0/sim/ila_0.v" \
"../../../../ip_clk_wiz_extend.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../ip_clk_wiz_extend.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../rtl/ip_clk_wiz_extend.v" \
"../../../../../sim/tb/tb_ip_clk_wiz_extend.v" \

# compile glbl module
F:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

