######################################################################
#
# File name : tb_ip_2port_ram.udo
# Created on: Sat Nov 02 18:36:30 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
