######################################################################
#
# File name : tb_ip_2port_ram_extend_simulate.do
# Created on: Sun Nov 03 15:13:25 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_ip_2port_ram_extend xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_ip_2port_ram_extend_wave.do}

view wave
view structure
view signals

do {tb_ip_2port_ram_extend.udo}

run 1000ns
