######################################################################
#
# File name : tb_ip_2port_ram_extend_wave.do
# Created on: Sun Nov 03 14:58:13 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
