######################################################################
#
# File name : tb_ip_2port_ram_extend_compile.do
# Created on: Sun Nov 03 15:13:22 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim\\win64\\vlib modelsim_lib/work
F:\\modelsim\\win64\\vlib modelsim_lib/msim

F:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../ip_2port_ram_extend.gen/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../../rtl/ip_2port_ram_extend.v" \
"../../../../../rtl/ram_rw.v" \
"../../../../../sim/tb/tb_ip_2port_ram_extend.v" \


# compile glbl module
F:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

