######################################################################
#
# File name : tb_ip_fifo_extend_simulate.do
# Created on: Fri Nov 15 02:14:11 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L fifo_generator_v13_2_5 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_ip_fifo_extend xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_ip_fifo_extend_wave.do}

view wave
view structure
view signals

do {tb_ip_fifo_extend.udo}

run 1000ns
