######################################################################
#
# File name : tb_ip_fifo_extend_wave.do
# Created on: Fri Nov 15 02:14:11 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
