# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/timer/timer.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer || ORIG_REF_NAME==timer} -quiet] -quiet

# IP: bd/timer/ip/timer_clk_wiz_0_0/timer_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_clk_wiz_0_0 || ORIG_REF_NAME==timer_clk_wiz_0_0} -quiet] -quiet

# IP: bd/timer/ip/timer_microblaze_0_0/timer_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_microblaze_0_0 || ORIG_REF_NAME==timer_microblaze_0_0} -quiet] -quiet

# IP: bd/timer/ip/timer_dlmb_v10_0/timer_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_dlmb_v10_0 || ORIG_REF_NAME==timer_dlmb_v10_0} -quiet] -quiet

# IP: bd/timer/ip/timer_ilmb_v10_0/timer_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_ilmb_v10_0 || ORIG_REF_NAME==timer_ilmb_v10_0} -quiet] -quiet

# IP: bd/timer/ip/timer_dlmb_bram_if_cntlr_0/timer_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==timer_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/timer/ip/timer_ilmb_bram_if_cntlr_0/timer_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==timer_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/timer/ip/timer_lmb_bram_0/timer_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_lmb_bram_0 || ORIG_REF_NAME==timer_lmb_bram_0} -quiet] -quiet

# IP: bd/timer/ip/timer_microblaze_0_axi_intc_0/timer_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_microblaze_0_axi_intc_0 || ORIG_REF_NAME==timer_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/timer/ip/timer_microblaze_0_xlconcat_0/timer_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_microblaze_0_xlconcat_0 || ORIG_REF_NAME==timer_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/timer/ip/timer_mdm_1_0/timer_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_mdm_1_0 || ORIG_REF_NAME==timer_mdm_1_0} -quiet] -quiet

# IP: bd/timer/ip/timer_rst_clk_wiz_0_100M_0/timer_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==timer_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/timer/ip/timer_axi_uartlite_0_0/timer_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_axi_uartlite_0_0 || ORIG_REF_NAME==timer_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/timer/ip/timer_PmodOLEDrgb_0_0/timer_PmodOLEDrgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_PmodOLEDrgb_0_0 || ORIG_REF_NAME==timer_PmodOLEDrgb_0_0} -quiet] -quiet

# IP: bd/timer/ip/timer_PmodHYGRO_0_0/timer_PmodHYGRO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_PmodHYGRO_0_0 || ORIG_REF_NAME==timer_PmodHYGRO_0_0} -quiet] -quiet

# IP: bd/timer/ip/timer_PmodALS_0_0/timer_PmodALS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_PmodALS_0_0 || ORIG_REF_NAME==timer_PmodALS_0_0} -quiet] -quiet

# IP: bd/timer/ip/timer_axi_timer_0_0/timer_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_axi_timer_0_0 || ORIG_REF_NAME==timer_axi_timer_0_0} -quiet] -quiet

# IP: bd/timer/ip/timer_xbar_2/timer_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_xbar_2 || ORIG_REF_NAME==timer_xbar_2} -quiet] -quiet

# IP: bd/timer/ip/timer_microblaze_0_axi_periph_2/timer_microblaze_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_microblaze_0_axi_periph_2 || ORIG_REF_NAME==timer_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/timer/ip/timer_axi_gpio_0_0/timer_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_axi_gpio_0_0 || ORIG_REF_NAME==timer_axi_gpio_0_0} -quiet] -quiet

# IP: bd/timer/ip/timer_axi_gpio_1_1/timer_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_axi_gpio_1_1 || ORIG_REF_NAME==timer_axi_gpio_1_1} -quiet] -quiet

# IP: bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_axi_gpio_2_0 || ORIG_REF_NAME==timer_axi_gpio_2_0} -quiet] -quiet

# XDC: bd/timer/timer_ooc.xdc
