# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA_projects/MicroBlaze/timer/timer.cache/wt [current_project]
set_property parent.project_path E:/FPGA_projects/MicroBlaze/timer/timer.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_repo_paths e:/vivado-library-master [current_project]
update_ip_catalog
set_property ip_output_repo e:/FPGA_projects/MicroBlaze/timer/timer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/hdl/timer_wrapper.v
add_files E:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/timer.bd
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_clk_wiz_0_0/timer_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_clk_wiz_0_0/timer_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_clk_wiz_0_0/timer_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_microblaze_0_0/timer_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_microblaze_0_0/timer_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_microblaze_0_0/timer_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_dlmb_v10_0/timer_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_dlmb_v10_0/timer_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_ilmb_v10_0/timer_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_ilmb_v10_0/timer_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_dlmb_bram_if_cntlr_0/timer_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_ilmb_bram_if_cntlr_0/timer_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_lmb_bram_0/timer_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_microblaze_0_axi_intc_0/timer_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_microblaze_0_axi_intc_0/timer_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_microblaze_0_axi_intc_0/timer_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_mdm_1_0/timer_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_mdm_1_0/timer_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_rst_clk_wiz_0_100M_0/timer_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_rst_clk_wiz_0_100M_0/timer_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_rst_clk_wiz_0_100M_0/timer_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_uartlite_0_0/timer_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_uartlite_0_0/timer_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_uartlite_0_0/timer_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodOLEDrgb_0_0/timer_PmodOLEDrgb_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodHYGRO_0_0/src/PmodHYGRO_pmod_bridge_0_0/PmodHYGRO_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodHYGRO_0_0/src/PmodHYGRO_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodHYGRO_0_0/src/PmodHYGRO_axi_timer_0_0/PmodHYGRO_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodHYGRO_0_0/src/PmodHYGRO_axi_timer_0_0/PmodHYGRO_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodHYGRO_0_0/src/PmodHYGRO_axi_iic_0_0/PmodHYGRO_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodHYGRO_0_0/src/PmodHYGRO_axi_iic_0_0/PmodHYGRO_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodHYGRO_0_0/timer_PmodHYGRO_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodHYGRO_0_0/src/PmodHYGRO_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodALS_0_0/src/PmodALS_pmod_bridge_0_0/PmodALS_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodALS_0_0/src/PmodALS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodALS_0_0/timer_PmodALS_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_PmodALS_0_0/src/PmodALS_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_timer_0_0/timer_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_timer_0_0/timer_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_xbar_2/timer_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_0_0/timer_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_0_0/timer_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_0_0/timer_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_1_1/timer_axi_gpio_1_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_1_1/timer_axi_gpio_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_1_1/timer_axi_gpio_1_1.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_axi_gpio_2_0/timer_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all E:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/timer_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/MicroBlaze/timer/timer.srcs/sources_1/bd/timer/ip/timer_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top timer_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef timer_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file timer_wrapper_utilization_synth.rpt -pb timer_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
