######################################################################
#
# File name : tb_ip_clk_wiz_compile.do
# Created on: Fri Oct 18 22:00:52 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim\\win64\\vlib modelsim_lib/work
F:\\modelsim\\win64\\vlib modelsim_lib/msim

F:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../ip_clk_wiz.gen/sources_1/ip/clk_wiz_0" \
"../../../../ip_clk_wiz.gen/sources_1/ip/ila_0/sim/ila_0.v" \
"../../../../ip_clk_wiz.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../ip_clk_wiz.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../rtl/ip_clk_wiz.v" \
"../../../../../sim/tb/tb_ip_clk_wiz.v" \


# compile glbl module
F:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

