######################################################################
#
# File name : tb_ip_clk_wiz.udo
# Created on: Thu Oct 17 18:23:46 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
