######################################################################
#
# File name : tb_ip_clk_wiz_wave.do
# Created on: Thu Oct 17 18:23:46 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
