######################################################################
#
# File name : tb_ip_fifo_compile.do
# Created on: Wed Nov 13 21:50:30 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim\\win64\\vlib modelsim_lib/work
F:\\modelsim\\win64\\vlib modelsim_lib/msim

F:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../ip_fifo.gen/sources_1/ip/clk_wiz_0" \
"../../../../ip_fifo.gen/sources_1/ip/fifo_generator_0/sim/fifo_generator_0.v" \
"../../../../ip_fifo.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../ip_fifo.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../rtl/fifo_rd.v" \
"../../../../../rtl/fifo_wr.v" \
"../../../../../rtl/ip_fifo.v" \
"../../../../../sim/tb/tb_ip_fifo.v" \


# compile glbl module
F:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

