######################################################################
#
# File name : tb_ip_fifo_wave.do
# Created on: Wed Nov 13 21:50:34 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
