######################################################################
#
# File name : tb_ip_1port_ram_wave.do
# Created on: Sat Oct 26 11:27:51 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
