######################################################################
#
# File name : tb_ip_1port_ram_simulate.do
# Created on: Sat Oct 26 11:27:51 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L blk_mem_gen_v8_4_4 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_ip_1port_ram xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_ip_1port_ram_wave.do}

view wave
view structure
view signals

do {tb_ip_1port_ram.udo}

run 1000ns
