######################################################################
#
# File name : tb_ip_1port_ram_compile.do
# Created on: Sat Oct 26 11:27:47 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim\\win64\\vlib modelsim_lib/work
F:\\modelsim\\win64\\vlib modelsim_lib/msim

F:\\modelsim\\win64\\vlib modelsim_lib/msim/xpm
F:\\modelsim\\win64\\vlib modelsim_lib/msim/blk_mem_gen_v8_4_4
F:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim\\win64\\vmap xpm modelsim_lib/msim/xpm
F:\\modelsim\\win64\\vmap blk_mem_gen_v8_4_4 modelsim_lib/msim/blk_mem_gen_v8_4_4
F:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim\\win64\\vlog  -incr -sv -work xpm  \
"F:/Vivado/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

F:\\modelsim\\win64\\vcom  -93 -work xpm  \
"F:/Vivado/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \

F:\\modelsim\\win64\\vlog  -incr -work blk_mem_gen_v8_4_4  \
"../../../../ip_1port_ram.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

F:\\modelsim\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../ip_1port_ram.gen/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../../rtl/ip_1port_ram.v" \
"../../../../../rtl/ram_rw.v" \
"../../../../../sim/tb/tb_ip_1port_ram.v" \

# compile glbl module
F:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

